# Generated by Django 3.2.4 on 2021-07-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRule',
            fields=[
                ('merchant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('calculation_rule_creditcard', models.CharField(blank=True, max_length=50, null=True)),
                ('calculation_rule_casa', models.CharField(blank=True, max_length=50, null=True)),
                ('calculation_rule_instant_pay', models.CharField(blank=True, max_length=50, null=True)),
                ('calculation_rule_setup_fees', models.CharField(blank=True, max_length=50, null=True)),
                ('is_live', models.BooleanField()),
                ('calculation_rule_minimum_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('calculation_rule_credit_card_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('calculation_rule_mandate_fee', models.CharField(blank=True, max_length=250, null=True)),
                ('calculation_rule_cc_discount', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'calculation_rule',
                'managed': False,
            },
        ),
    ]
